commerce_payment.commerce_payment_gateway.plugin.commerce_paypal_ec:
  type: commerce_payment_gateway_configuration
  mapping:
    client_id:
      type: string
      label: 'REST Client ID'
    client_secret:
      type: string
      label: 'REST Client Secret'
